name: gloria docs
tagline: A simple static website generator
baseurl: https://gloria.js.org
author: daveed
description: Documentation for the tool gloriajs
dest: build
css: tailwind
include:
    - layouts
    - pages
    # - posts
    # - data
copy:
    - public
exclude:
    - .draft.md
version: 3
