name: gloria-docs
tagline: 'A simple static website generator'
baseurl: 'https://gloriajs.github.io'
gems:
    - jekyll-paginate
markdown: kramdown
location: gloria-docs
longname: 'Gloria docs'
layout: bootstrap
author: 'david silva'
description: 'Documentation for the tool gloriajs'
version: 0.4.0
dest: build
theme: architect
