name: gloria docs
tagline: 'A simple static website generator'
baseurl: 'https://gloriajs.github.io'
author: 'daveed silva'
description: Documentation for the tool gloriajs
dest: build
css: tailwind
include:
    - pages
    - posts
    - data
copy:
    - public
exclude:
    - .draft.md
version: 2.0.4
